import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="min-h-full bg-gray-300">
      <Head>
        <title>OverLap Navigation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="max-w-8xl my-20 mx-10 max-h-full bg-white py-6 sm:px-6 lg:px-8 absolute z-10 top-20 right-0 bottom-0 left-0 rounded-lg">
          <div className="px-4 py-6 sm:px-0 h-full">
            <div className="border-4 border-dashed border-gray-200 rounded-lg h-full" />
          </div>
        </div>
      </main>
    </div>
  );
}
